export const player = 'Billy'
export const player2 = 'Bob'
export const cleavageTitle = 'Les mouchoirs en tissu'
export const integrationTestMessage = 'Integration Test Message'
export const username = 'Ben'
export const token = 'f6s53d4gsd3f4sddfd'
export const channel = 'BenChannel'
