/* eslint-disable no-unused-vars */
export enum InterfaceView {
NONE='NONE',
CONNECT_CHAT='CONNECT_CHAT',
MAIN_MENU='MAIN_MENU',
INTRO='INTRO',
SETTINGS='SETTINGS',
ABOUT='ABOUT',
CREDITS='CREDITS',
GAME='GAME',
STREAMERS='STREAMERS'
}
