/* eslint-disable no-unused-vars */
export enum InterfaceView {
NONE='NONE',
CONNECT_CHAT='CONNECT_CHAT',
NEW_CLEAVAGE='NEW_CLEAVAGE',
CURRENT_CLEAVAGE='CURRENT_CLEAVAGE',
MAIN_MENU='MAIN_MENU',
STUDIO='STUDIO',
SETTINGS='SETTINGS',
ABOUT='ABOUT'
}
