
export enum EventType {
    CONNECT_CHAT = "CONNECT_CHAT",
    DISCONNECT_CHAT = "DISCONNECT_CHAT",
    NEW_CLEAVAGE = "NEW_CLEAVAGE",
    LAUNCH_CLEAVAGE = "LAUNCH_CLEAVAGE",
    PLAYER_CLEAVE = "PLAYER_CLEAVE",
    PLAYER_MESSAGE = "PLAYER_MESSAGE"
}
