/* eslint-disable no-unused-vars */

export enum EventType {
    CONNECT_CHAT = 'CONNECT_CHAT',
    DISCONNECT_CHAT = 'DISCONNECT_CHAT',
    NEW_CLEAVAGE = 'NEW_CLEAVAGE',
    LAUNCH_CLEAVAGE = 'LAUNCH_CLEAVAGE',
    PLAYER_CLEAVE = 'PLAYER_CLEAVE',
    PLAYER_MESSAGE = 'PLAYER_MESSAGE',
    DRAW_CLEAVAGE = 'DRAW_CLEAVAGE',
    PLAYER_SUGGEST_CLEAVAGE = 'SUGGEST_CLEAVAGE',
    PLAYER_ASK_FOR_HELP = 'PLAYER_ASK_FOR_HELP',
    CANCEL_CLEAVAGE = 'CANCEL_CLEAVAGE',
    PLAYER_HYPERLIKE = 'PLAYER_HYPERLIKE',
    PLAYER_APPLAUSE = 'PLAYER_APPLAUSE',
    PLAYER_SHOOT = 'PLAYER_SHOOT',
    PLAYER_WHISTLE = 'PLAYER_WHISTLE',
    APPLICATION_START = 'APPLICATION_START',
    NAVIGATE = 'NAVIGATE',
    CHANGE_MUSIC_VOLUME = 'CHANGE_MUSIC_VOLUME',
    CHANGE_SOUND_VOLUME = 'CHANGE_SOUND_VOLUME',
    PLAYER_QUIT = 'PLAYER_QUIT',
    START_AUTOPLAY = 'START_AUTOPLAY',
    CHECK_AUTOPLAY = 'CHECK_AUTOPLAY',
    STOP_AUTOPLAY = 'STOP_AUTOPLAY',
    DRAW_GLOBAL_CLEAVAGE_DRAWPILE = 'DRAW_GLOBAL_CLEAVAGE_DRAWPILE',
    SAVE_CLEAVAGE_ON_GLOBAL_CLEAVAGE_DRAWPILE = 'SAVE_CLEAVAGE_ON_GLOBAL_CLEAVAGE_DRAWPILE'
}
