/* eslint-disable no-unused-vars */

export enum EventType {
    CONNECT_CHAT = 'CONNECT_CHAT',
    DISCONNECT_CHAT = 'DISCONNECT_CHAT',
    NEW_CLEAVAGE = 'NEW_CLEAVAGE',
    LAUNCH_CLEAVAGE = 'LAUNCH_CLEAVAGE',
    PLAYER_CLEAVE = 'PLAYER_CLEAVE',
    PLAYER_MESSAGE = 'PLAYER_MESSAGE',
    PUBLIC_CLEAVAGE = 'PUBLIC_CLEAVAGE',
    PLAYER_SUGGEST_CLEAVAGE = 'SUGGEST_CLEAVAGE',
    PLAYER_ASK_FOR_HELP = 'PLAYER_ASK_FOR_HELP',
    CANCEL_CLEAVAGE = 'CANCEL_CLEAVAGE',
    PLAYER_HYPERLIKE = 'PLAYER_HYPERLIKE',
    PLAYER_APPLAUSE = 'PLAYER_APPLAUSE',
    PLAYER_SHOOT = 'PLAYER_SHOOT',
    PLAYER_WHISTLE = 'PLAYER_WHISTLE',
    APPLICATION_START = 'APPLICATION_START',
    NAVIGATE = 'NAVIGATE'
}
