name: CI workflow
on: [push]
jobs:
  acceptance_test:
    name: Acceptance Test Suites
    runs-on : ubuntu-latest
    env:
      TWITCHUSERNAME: benjaminbohec
      TWITCHTOKEN: ${{ secrets.TWITCHTOKEN }}
      TWITCHCHANNEL: benjaminbohec
      BACKEND_SHEME: http
      BACKEND_FQDN: "localhost"
      PORT: 8080
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_CLIENT_EMAIL: ${{ secrets.GCP_CLIENT_EMAIL }}
      GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run test -- -g "Feature:"
  integration_test:
    name: Integration Test Suites
    runs-on : ubuntu-latest
    env:
      TWITCHUSERNAME: benjaminbohec
      TWITCHTOKEN: ${{ secrets.TWITCHTOKEN }}
      TWITCHCHANNEL: benjaminbohec
      BACKEND_SHEME: http
      BACKEND_FQDN: "localhost"
      PORT: 8080
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_CLIENT_EMAIL: ${{ secrets.GCP_CLIENT_EMAIL }}
      GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run test -- -g "Integration Test - Global Cleavage Draw Pile Repository|Integration Test - Chat Gateway"
  build_and_deploy_Docker_container_on_GCP_Cloud_Run:
    name: Build Docker Image
    runs-on : ubuntu-latest
    env:
      PRODUCTION_URL: lejeuduclivage.com
      TWITCHUSERNAME: benjaminbohec
      TWITCHTOKEN: ${{ secrets.TWITCHTOKEN }}
      TWITCHCHANNEL: benjaminbohec
      BACKEND_SHEME: https
      BACKEND_FQDN: ${{ github.ref_name }}.lejeuduclivage.com
      PORT: 8080
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_CLIENT_EMAIL: ${{ secrets.GCP_CLIENT_EMAIL }}
      GCP_PRIVATE_KEY: ${{ secrets.GCP_PRIVATE_KEY }}
      GCP_CLOUDRUN_SERVICE: ${{ secrets.GCP_PROJECT_ID }}-${{ github.ref_name }}
      GCP_REGION: us-central1
    permissions:
      deployments: write
    steps:
      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: gitHubDeployment
        with:
          token: '${{ github.token }}'
          environment: ${{ github.ref_name }}
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - name: Git checkout on branch ${{ github.ref_name }}
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build server
        run: npm run build:server
      - name: Build client
        run: npm run build:client
      - name: Build docker container from Dockerfile
        run: docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_CLOUDRUN_SERVICE }}:${{  github.sha }} .
      - name: GitHub deployment - In Progress
        uses: chrnorm/deployment-status@v2
        id: deployment_in_progress
        with:
          token: '${{ github.token }}'
          deployment-id: ${{ steps.gitHubDeployment.outputs.deployment_id }}
          state: 'in_progress'
      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_JSON }}'
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Install gcloud beta component
        run: gcloud components install --quiet beta
      - name: Authorize Docker push on Google Cloud container registry
        run: gcloud auth configure-docker
      - name: Push Container to Google Cloud Storage
        run: docker push gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_CLOUDRUN_SERVICE }}:${{  github.sha }}
      - name: Update GCP Secrets
        run: printf ${{ secrets.GCP_PRIVATE_KEY }} | gcloud beta secrets versions add GCP_PRIVATE_KEY --data-file=-
      - name: Deploy to Google Cloud Platform - Cloud Run
        id: gcpCloudRunDeploy
        run: >
          echo "::set-output name=url::$(
          gcloud beta run deploy ${{ env.GCP_CLOUDRUN_SERVICE }}
          --image=gcr.io/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_CLOUDRUN_SERVICE }}:${{  github.sha }}
          --quiet
          --platform=managed
          --region=${{ env.GCP_REGION }}
          --update-env-vars=GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }},GCP_CLIENT_EMAIL=${{ secrets.GCP_CLIENT_EMAIL }}
          --update-secrets=GCP_PRIVATE_KEY=GCP_PRIVATE_KEY:latest
          --project=${{ env.GCP_PROJECT_ID }}
          --memory=256Mi
          --min-instances=0
          --max-instances=1
          --concurrency=1000
          --allow-unauthenticated
          --format="value(status.url)"
          )"
      - name: Update GCP Cloud Run domain mappings
        if: ${{ github.ref_name }} == 'main'
        run: |
          gcloud domains verify ${{ env.PRODUCTION_URL }}
          gcloud beta run domain-mappings create --service=${{ env.GCP_CLOUDRUN_SERVICE }} --domain=${{ env.PRODUCTION_URL }} --region ${{ env.GCP_REGION }}
          gcloud beta run domain-mappings create --service=${{ env.GCP_CLOUDRUN_SERVICE }} --domain=www.${{ env.PRODUCTION_URL }} --region ${{ env.GCP_REGION }}
      - name: GitHub deployment - Success
        if: success()
        uses: chrnorm/deployment-status@v2
        id: deployment_success
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.gcpCloudRunDeploy.outputs.url }}
          deployment-id: ${{ steps.gitHubDeployment.outputs.deployment_id }}
          state: 'success'
      - name: GitHub deployment - Failed
        if: failure()
        uses: chrnorm/deployment-status@v2
        id: deployment_failed
        with:
          token: '${{ github.token }}'
          deployment-id: ${{ steps.gitHubDeployment.outputs.deployment_id }}
          state: 'failure'