name: Testing workflow
on: [push]
jobs:
  test:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.4.2
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run test -- -g "Feature"